version: "3"
services:
  bwalink:
    # was from latest
    # this one is custom image built on Joonas's computer for arm/v7 support
    image: 5d40b2c71e6b
    restart: unless-stopped
    network_mode: host
    environment:
      # See https://iotbyhvm.ooo/using-uris-to-connect-to-a-mqtt-server/ for MQTT_URI format
      # MQTT_URI *must* be properly URI encoded, e.g. mqtt://useename:pa##word@10.1.10.2 would 
      # be mqtt://username:pa%23%23word@10.1.10.2
      # BRIDGE_IP and BRIDGE_PORT are the address and port for your serial to IP device or 
      # host running ser2net, socat or ESPEasy serial server
      MQTT_URI: mqtt://localhost
      BRIDGE_IP: 192.168.1.254
      BRIDGE_PORT: 4196
      TZ: Europe/Helsinki
      LOG_LEVEL: WARN # Any of FATAL, ERROR, WARN, INFO or DEBUG
