version: "3"

services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/pi/joonas-iot/henkan-poreamme/docker-compose-configs/home-asssistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host
    # older Docker daemon had some problem with seccomp
    security_opt:
      - seccomp=unconfined

